export const themeClassMap = {
  light: {
    primary: "bg-blue-500",
    secondary: "bg-blue-300",
    accent: "bg-yellow-400",
    base: "bg-white text-black",
    border: "border-blue-400",
  },
  dark: {
    primary: "bg-gray-800",
    secondary: "bg-gray-700",
    accent: "bg-purple-500",
    base: "bg-gray-900 text-white",
    border: "border-gray-600",
  },
  cupcake: {
    primary: "bg-pink-400",
    secondary: "bg-fuchsia-300",
    accent: "bg-yellow-300",
    base: "bg-pink-50 text-pink-800",
    border: "border-pink-300",
  },
  bumblebee: {
    primary: "bg-yellow-600",
    secondary: "bg-gray-900",
    accent: "bg-yellow-400",
    base: "bg-yellow-100 text-yellow-900",
    border: "border-yellow-500",
  },
  emerald: {
    primary: "bg-emerald-500",
    secondary: "bg-green-400",
    accent: "bg-teal-300",
    base: "bg-emerald-50 text-emerald-900",
    border: "border-emerald-400",
  },
  corporate: {
    primary: "bg-blue-600",
    secondary: "bg-blue-300",
    accent: "bg-gray-200",
    base: "bg-blue-50 text-blue-900",
    border: "border-blue-300",
  },
  synthwave: {
    primary: "bg-pink-500",
    secondary: "bg-purple-600",
    accent: "bg-yellow-400",
    base: "bg-purple-900 text-pink-200",
    border: "border-purple-700",
  },
  retro: {
    primary: "bg-orange-300",
    secondary: "bg-lime-300",
    accent: "bg-yellow-300",
    base: "bg-yellow-50 text-yellow-900",
    border: "border-yellow-300",
  },
  cyberpunk: {
    primary: "bg-yellow-400",
    secondary: "bg-pink-600",
    accent: "bg-cyan-400",
    base: "bg-yellow-50 text-pink-800",
    border: "border-yellow-300",
  },
  valentine: {
    primary: "bg-pink-500",
    secondary: "bg-red-400",
    accent: "bg-fuchsia-300",
    base: "bg-pink-200 text-red-800",
    border: "border-pink-400",
  },
  halloween: {
    primary: "bg-orange-700",
    secondary: "bg-black",
    accent: "bg-orange-300",
    base: "bg-orange-900 text-orange-100",
    border: "border-orange-700",
  },
  garden: {
    primary: "bg-green-500",
    secondary: "bg-lime-300",
    accent: "bg-emerald-400",
    base: "bg-green-100 text-green-900",
    border: "border-green-400",
  },
  forest: {
    primary: "bg-green-700",
    secondary: "bg-emerald-500",
    accent: "bg-lime-400",
    base: "bg-green-900 text-green-100",
    border: "border-green-800",
  },
  aqua: {
    primary: "bg-cyan-400",
    secondary: "bg-blue-300",
    accent: "bg-teal-300",
    base: "bg-cyan-100 text-cyan-900",
    border: "border-cyan-300",
  },
  lofi: {
    primary: "bg-gray-600",
    secondary: "bg-gray-400",
    accent: "bg-gray-300",
    base: "bg-gray-200 text-gray-800",
    border: "border-gray-400",
  },
  pastel: {
    primary: "bg-pink-300",
    secondary: "bg-green-200",
    accent: "bg-sky-300",
    base: "bg-pink-100 text-pink-800",
    border: "border-pink-200",
  },
  fantasy: {
    primary: "bg-fuchsia-500",
    secondary: "bg-purple-300",
    accent: "bg-indigo-300",
    base: "bg-fuchsia-100 text-fuchsia-900",
    border: "border-fuchsia-300",
  },
  wireframe: {
    primary: "bg-gray-400",
    secondary: "bg-gray-300",
    accent: "bg-gray-200",
    base: "bg-white text-gray-700",
    border: "border-gray-300",
  },
  black: {
    primary: "bg-black",
    secondary: "bg-zinc-700",
    accent: "bg-zinc-600",
    base: "bg-black text-white",
    border: "border-zinc-800",
  },
  luxury: {
    primary: "bg-yellow-400",
    secondary: "bg-gray-800",
    accent: "bg-gray-600",
    base: "bg-gray-900 text-yellow-300",
    border: "border-gray-700",
  },
  dracula: {
    primary: "bg-purple-500",
    secondary: "bg-pink-400",
    accent: "bg-cyan-400",
    base: "bg-[#282a36] text-[#f8f8f2]",
    border: "border-[#44475a]",
  },
  cmyk: {
    primary: "bg-cyan-500",
    secondary: "bg-pink-500",
    accent: "bg-yellow-400",
    base: "bg-white text-cyan-800",
    border: "border-gray-300",
  },
  autumn: {
    primary: "bg-orange-600",
    secondary: "bg-yellow-500",
    accent: "bg-red-400",
    base: "bg-orange-100 text-orange-900",
    border: "border-orange-400",
  },
  business: {
    primary: "bg-blue-800",
    secondary: "bg-gray-800",
    accent: "bg-indigo-500",
    base: "bg-slate-900 text-slate-100",
    border: "border-slate-700",
  },
  acid: {
    primary: "bg-lime-400",
    secondary: "bg-yellow-300",
    accent: "bg-pink-400",
    base: "bg-lime-100 text-lime-800",
    border: "border-lime-300",
  },
  lemonade: {
    primary: "bg-yellow-300",
    secondary: "bg-lime-300",
    accent: "bg-teal-300",
    base: "bg-yellow-50 text-yellow-800",
    border: "border-yellow-200",
  },
  night: {
    primary: "bg-blue-900",
    secondary: "bg-slate-800",
    accent: "bg-purple-600",
    base: "bg-gray-900 text-gray-200",
    border: "border-gray-700",
  },
  coffee: {
    primary: "bg-stone-700",
    secondary: "bg-amber-500",
    accent: "bg-orange-400",
    base: "bg-stone-900 text-amber-100",
    border: "border-stone-800",
  },
  winter: {
    primary: "bg-blue-200",
    secondary: "bg-blue-400",
    accent: "bg-cyan-300",
    base: "bg-blue-50 text-blue-800",
    border: "border-blue-200",
  },
  dim: {
    primary: "bg-gray-700",
    secondary: "bg-gray-600",
    accent: "bg-gray-500",
    base: "bg-gray-800 text-gray-200",
    border: "border-gray-700",
  },
  nord: {
    primary: "bg-[#5e81ac]",
    secondary: "bg-[#81a1c1]",
    accent: "bg-[#88c0d0]",
    base: "bg-[#2e3440] text-[#d8dee9]",
    border: "border-[#4c566a]",
  },
  sunset: {
    primary: "bg-red-400",
    secondary: "bg-orange-300",
    accent: "bg-yellow-400",
    base: "bg-orange-200 text-red-900",
    border: "border-orange-300",
  },
  ocean: {
    primary: "bg-cyan-600",
    secondary: "bg-blue-400",
    accent: "bg-teal-400",
    base: "bg-blue-50 text-blue-900",
    border: "border-blue-200",
  },
  rose: {
    primary: "bg-rose-500",
    secondary: "bg-pink-300",
    accent: "bg-fuchsia-400",
    base: "bg-rose-50 text-rose-900",
    border: "border-rose-300",
  },
  midnight: {
    primary: "bg-gray-800",
    secondary: "bg-indigo-700",
    accent: "bg-purple-600",
    base: "bg-black text-gray-100",
    border: "border-gray-800",
  },
  lavender: {
    primary: "bg-purple-300",
    secondary: "bg-violet-200",
    accent: "bg-pink-200",
    base: "bg-purple-50 text-purple-900",
    border: "border-purple-200",
  },
  coral: {
    primary: "bg-orange-400",
    secondary: "bg-red-300",
    accent: "bg-yellow-300",
    base: "bg-orange-50 text-orange-900",
    border: "border-orange-200",
  },
  steel: {
    primary: "bg-gray-500",
    secondary: "bg-gray-400",
    accent: "bg-slate-300",
    base: "bg-gray-100 text-gray-800",
    border: "border-gray-300",
  },
  mint: {
    primary: "bg-emerald-300",
    secondary: "bg-teal-200",
    accent: "bg-green-200",
    base: "bg-green-50 text-green-900",
    border: "border-emerald-300",
  },
  graphite: {
    primary: "bg-zinc-800",
    secondary: "bg-zinc-600",
    accent: "bg-neutral-500",
    base: "bg-zinc-900 text-zinc-100",
    border: "border-zinc-700",
  },
  blossom: {
    primary: "bg-pink-400",
    secondary: "bg-rose-200",
    accent: "bg-fuchsia-300",
    base: "bg-pink-50 text-rose-800",
    border: "border-pink-300",
  },
  sunrise: {
    primary: "bg-orange-400",
    secondary: "bg-yellow-300",
    accent: "bg-red-300",
    base: "bg-yellow-50 text-orange-900",
    border: "border-yellow-300",
  },
  evergreen: {
    primary: "bg-green-700",
    secondary: "bg-lime-400",
    accent: "bg-emerald-300",
    base: "bg-green-100 text-green-900",
    border: "border-green-400",
  },
  nebula: {
    primary: "bg-purple-700",
    secondary: "bg-indigo-600",
    accent: "bg-blue-400",
    base: "bg-gray-900 text-purple-100",
    border: "border-indigo-500",
  },
  canyon: {
    primary: "bg-red-800",
    secondary: "bg-orange-700",
    accent: "bg-amber-400",
    base: "bg-orange-100 text-red-900",
    border: "border-orange-600",
  },
  bamboo: {
    primary: "bg-lime-700",
    secondary: "bg-emerald-400",
    accent: "bg-green-200",
    base: "bg-lime-100 text-lime-900",
    border: "border-lime-500",
  },
  galaxy: {
    primary: "bg-black",
    secondary: "bg-indigo-800",
    accent: "bg-purple-500",
    base: "bg-gray-950 text-indigo-200",
    border: "border-indigo-700",
  },
  sunflower: {
    primary: "bg-yellow-500",
    secondary: "bg-yellow-300",
    accent: "bg-orange-300",
    base: "bg-yellow-50 text-yellow-900",
    border: "border-yellow-400",
  },
  ink: {
    primary: "bg-gray-900",
    secondary: "bg-gray-700",
    accent: "bg-gray-500",
    base: "bg-gray-950 text-gray-100",
    border: "border-gray-800",
  },
  denim: {
    primary: "bg-blue-700",
    secondary: "bg-sky-600",
    accent: "bg-indigo-400",
    base: "bg-blue-100 text-blue-900",
    border: "border-blue-500",
  },
  coralreef: {
    primary: "bg-pink-400",
    secondary: "bg-orange-300",
    accent: "bg-yellow-300",
    base: "bg-pink-50 text-pink-900",
    border: "border-pink-400",
  },
  flamingo: {
    primary: "bg-pink-500",
    secondary: "bg-fuchsia-400",
    accent: "bg-red-300",
    base: "bg-rose-100 text-rose-900",
    border: "border-pink-500",
  },
  aurora: {
    primary: "bg-green-400",
    secondary: "bg-cyan-400",
    accent: "bg-purple-300",
    base: "bg-gray-900 text-green-100",
    border: "border-cyan-500",
  },
  peachy: {
    primary: "bg-orange-300",
    secondary: "bg-pink-200",
    accent: "bg-yellow-300",
    base: "bg-orange-50 text-orange-900",
    border: "border-orange-200",
  },
};

export const THEMES = Object.keys(themeClassMap);
